# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 12:41
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', ckeditor.fields.RichTextField()),
                ('a_link', models.CharField(max_length=50)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', ckeditor.fields.RichTextField()),
                ('a_link', models.CharField(max_length=50)),
                ('timestamp', models.DateField()),
                ('img_patch', models.FileField(upload_to=b'advertisment/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('message_title', models.CharField(max_length=50)),
                ('message_context', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_title', models.TextField()),
                ('legal_context', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', ckeditor.fields.RichTextField()),
                ('a_link', models.CharField(max_length=50)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.TextField()),
                ('notice_context', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='author_text',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2016, 3, 2, 12, 41, 37, 522882, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='img_patch',
            field=models.FileField(default=datetime.datetime(2016, 3, 2, 12, 41, 40, 287372, tzinfo=utc), upload_to=b'authors/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2016, 3, 2, 12, 41, 41, 729539, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2016, 3, 2, 12, 41, 43, 11536, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='img_patch',
            field=models.FileField(default=datetime.datetime(2016, 3, 2, 12, 41, 44, 882639, tzinfo=utc), upload_to=b'documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='img_patch_review',
            field=models.FileField(default=datetime.datetime(2016, 3, 2, 12, 41, 46, 282504, tzinfo=utc), upload_to=b'review/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review_message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
